name: heartcare_plus
description: "heartcare_plus"

publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  image: ^4.5.4
  http: ^1.5.0
  image_picker: ^1.2.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  form_field_validator: ^1.1.0
  table_calendar: ^3.0.9
  intl: ^0.20.2
  auto_size_text: ^3.0.0
  flutter_tts: ^4.2.3

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/