name: heartcare_plus
description: "heartcare_plus"

publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  image: ^4.5.4
  http: ^1.5.0
  image_picker: ^1.2.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  form_field_validator: ^1.1.0
  table_calendar: ^3.0.9
  intl: ^0.20.2
  auto_size_text: ^3.0.0
  flutter_tts: ^4.2.3
  connectivity_plus: ^7.0.0
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  lottie: ^3.3.2
  internet_connection_checker: ^1.0.0+1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_plugin_android_lifecycle: ^2.0.30

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logoapp.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/lottie/
    - assets/