name: heartcare_plus
description: "heartcare_plus"

publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  form_field_validator: ^1.1.0
  table_calendar: ^3.0.9
  intl: ^0.20.2
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Doctor.png
    - assets/medic.jpg